# Generated by Django 3.0.4 on 2020-05-05 09:10

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='advantages/')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=32)),
                ('bio', models.TextField(blank=True)),
                ('avatar', imagekit.models.fields.ProcessedImageField(upload_to='avatars/', verbose_name='Фото сотрудника')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='main_slider/', verbose_name='Изображение')),
                ('url', models.URLField(max_length=255, verbose_name='Подробнее по ссылке')),
            ],
        ),
        migrations.CreateModel(
            name='NumberWithText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('logo', imagekit.models.fields.ProcessedImageField(upload_to='partners/', verbose_name='Логотип')),
                ('url', models.URLField(max_length=255, verbose_name='Сайт партнёра')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='projects/')),
            ],
        ),
    ]
