# Generated by Django 3.0.4 on 2020-04-03 15:04

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='main_slider/', verbose_name='Изображение')),
                ('url', models.URLField(max_length=255, verbose_name='Подробнее по ссылке')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('logo', imagekit.models.fields.ProcessedImageField(upload_to='partners/', verbose_name='Логотип')),
                ('url', models.URLField(max_length=255, verbose_name='Сайт партнёра')),
            ],
        ),
    ]
