# Generated by Django 3.0.4 on 2020-04-04 12:16

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=32)),
                ('bio', models.TextField()),
                ('avatar', imagekit.models.fields.ProcessedImageField(upload_to='avatars/', verbose_name='Фото сотрудника')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
