# Generated by Django 3.0.4 on 2020-04-04 19:11

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_employeecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='advantages/')),
            ],
        ),
        migrations.AlterField(
            model_name='employeecard',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
