# Generated by Django 3.0.4 on 2020-04-07 10:45

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20200404_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberWithText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='projects/')),
            ],
        ),
    ]
