image: docker:19.03.1
services:
  - docker:19.03.1-dind
stages:
- build
- deploy_stage

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:latest

build_stage:
  stage: build
  only:
    - master
    - /v\d+\.\d+\.\d+/
  script:
    - export BE_IMAGE_TAG=$(echo "$CI_COMMIT_TAG" | sed 's/^v*//')
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest
    - |
      case "$CI_COMMIT_TAG" in
        v*) docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$BE_IMAGE_TAG;
            docker push $CI_REGISTRY_IMAGE:$BE_IMAGE_TAG;;
      esac

deploy_stage:
  stage: deploy_stage
  image: alpine
  services: []
  only:
    - master
    - /v\d+\.\d+\.\d+/
  variables:
    NOTY_MESSAGE: "✅ Backend Stage Deployed ($CI_COMMIT_TAG): $CI_COMMIT_MESSAGE"
  script:
    - apk --no-cache add curl sshpass openssh-client
    - export SSHPASS="$USER_PASS"
    - sshpass -e ssh -p $USER_PORT -o stricthostkeychecking=no $USER_HOST "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - sshpass -e ssh -p $USER_PORT -o stricthostkeychecking=no $USER_HOST "cd /root && docker-compose pull backend
     && docker-compose down && docker-compose up -d"