# Generated by Django 3.0.4 on 2020-04-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('new_price', models.PositiveIntegerField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('is_discount', models.BooleanField(default=False)),
            ],
        ),
    ]
