# Generated by Django 3.0.4 on 2020-05-05 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200407_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=64)),
                ('buyer_phone', models.CharField(max_length=16)),
                ('comment', models.CharField(max_length=255)),
                ('products', models.ManyToManyField(related_name='order', to='catalog.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='category',
        ),
        migrations.AddField(
            model_name='parameter',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='value',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ParameterValue',
        ),
    ]
