# Generated by Django 3.0.4 on 2020-07-21 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200505_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='thickness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Thickness'),
        ),
    ]
