# Generated by Django 3.0.4 on 2020-07-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200721_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_thin',
            field=models.BooleanField(default=False),
        ),
    ]
