# Generated by Django 3.0.4 on 2020-07-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200722_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
