# Generated by Django 3.0.4 on 2020-07-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='count',
            new_name='quantity',
        ),
    ]
